@startuml
    interface Employee {
        +showDetails()
    }

    class Developer
    class Manager

    Employee <|.. Developer
    Employee <|.. Manager
    Manager --> Employee : contains
    @enduml