@startuml
    abstract class Notification {
        +notifyUser()
    }
    class EmailNotification
    class SMSNotification
    class NotificationFactory

    Notification <|-- EmailNotification
    Notification <|-- SMSNotification
    NotificationFactory --> Notification
    @enduml